[package]
name = "three"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.96"
bytes = "1.10.0"
data-encoding = "2.8.0"
ed25519-dalek = "2.1.1"
eframe = { version = "0.31.0", features = [
  "default_fonts",
  "glow",
  "persistence",
] }
egui = "0.31.0"
futures-lite = "2.6.0"
iroh = "0.33.0"
iroh-blobs = { version = "0.33.0", features = ["rpc"] }
iroh-gossip = "0.33.0"
postcard = "1.1.1"
rand = "0.8.5"
serde = { version = "1.0.218", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
